[project]
authors = ["Rafael Rodríguez"]
entry = "main.sw"
license = "Apache-2.0"
name = "my-fuel-project"

[dependencies]
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.5.0" }